/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface LoveLedgerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "injectVolume"
      | "operator"
      | "routeToTreasury"
      | "vestedVolume"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "VolumeInjected"): EventFragment;

  encodeFunctionData(
    functionFragment: "injectVolume",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "operator", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "routeToTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vestedVolume",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "injectVolume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "operator", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "routeToTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vestedVolume",
    data: BytesLike
  ): Result;
}

export namespace VolumeInjectedEvent {
  export type InputTuple = [
    donor: AddressLike,
    volumeAdded: BigNumberish,
    totalVolume: BigNumberish
  ];
  export type OutputTuple = [
    donor: string,
    volumeAdded: bigint,
    totalVolume: bigint
  ];
  export interface OutputObject {
    donor: string;
    volumeAdded: bigint;
    totalVolume: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LoveLedger extends BaseContract {
  connect(runner?: ContractRunner | null): LoveLedger;
  waitForDeployment(): Promise<this>;

  interface: LoveLedgerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  injectVolume: TypedContractMethod<
    [usdVolume: BigNumberish],
    [void],
    "payable"
  >;

  operator: TypedContractMethod<[], [string], "view">;

  routeToTreasury: TypedContractMethod<
    [treasury: AddressLike],
    [void],
    "nonpayable"
  >;

  vestedVolume: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "injectVolume"
  ): TypedContractMethod<[usdVolume: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "operator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "routeToTreasury"
  ): TypedContractMethod<[treasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vestedVolume"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "VolumeInjected"
  ): TypedContractEvent<
    VolumeInjectedEvent.InputTuple,
    VolumeInjectedEvent.OutputTuple,
    VolumeInjectedEvent.OutputObject
  >;

  filters: {
    "VolumeInjected(address,uint256,uint256)": TypedContractEvent<
      VolumeInjectedEvent.InputTuple,
      VolumeInjectedEvent.OutputTuple,
      VolumeInjectedEvent.OutputObject
    >;
    VolumeInjected: TypedContractEvent<
      VolumeInjectedEvent.InputTuple,
      VolumeInjectedEvent.OutputTuple,
      VolumeInjectedEvent.OutputObject
    >;
  };
}
